name: codeunion
description: Codeunion task app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  codeunion_ui:
    path: packages/codeunion_ui
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.8.4
  flutter_secure_storage: ^8.0.0
  formz: ^0.6.0
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  user_repository:
    path: packages/user_repository

assets:
    - assets/logo.png

    
dev_dependencies:
  bloc_test: ^9.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
